### PR TITLE
Direct link to the running demo ;)

### PR DESCRIPTION
**Pull request by kzu**
Thanks for this awesome demo!

### CODE REVIEW

**Comment by bennadel** [comment]
@danielkzu Hey man, thanks for the pull request. Sorry for not getting back to you sooner. As much as I love committing to GitHub, I don't actually know my way around the app that much. I _just_ saw your pull request today for the first time. Apparently, my email notifications are not working very well [at all]. 

I'll rock in the morning.... when I figure out how Pull Requests work :D

**Comment by kzu** [comment]
Hehe, no worries, it takes time.

You can typically just auto merge pull requests directly from the website ;)

**Comment by bennadel** [comment]
@danielkzu awesome! That was wicked easy :) I wanted to try using the command-line approach; but, since the change was so small, I just hit the button. Magic!!

**Comment by kzu** [comment]
It's a total winner feature. I sometimes even auto-merge from my phone when code contributions are small and I can "compile" them just by scanning the pull request changes :)

**Comment by bennadel** [comment]
I really gotta dig through the GitHub tutorials / help pages. I am sure there is a vast amount of awesome sauce that I am not taking advantage of yet!

**Pull request merged**
